# Generated by Django 2.2.4 on 2019-12-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('light_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SensorHumidityIndoor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SensorTemperatureIndoor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('temperature', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorTemperatureOutdoor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Thermostat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('thermostat_mode', models.CharField(choices=[('OFF', 'Off'), ('COOL', 'Cool'), ('HEAT', 'Heat'), ('FAN_OFF', 'Fan-on'), ('AUTO', 'Auto')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('light', models.ManyToManyField(to='parity_app.Light')),
                ('sensor_temperature_indoor', models.ManyToManyField(to='parity_app.SensorTemperatureIndoor')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('room', models.ManyToManyField(to='parity_app.Room')),
                ('thermostat', models.ManyToManyField(to='parity_app.Thermostat')),
            ],
        ),
    ]
