# Generated by Django 2.2.4 on 2019-12-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parity_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='room',
            field=models.ManyToManyField(blank=True, to='parity_app.Room'),
        ),
        migrations.AlterField(
            model_name='house',
            name='thermostat',
            field=models.ManyToManyField(blank=True, to='parity_app.Thermostat'),
        ),
        migrations.AlterField(
            model_name='room',
            name='light',
            field=models.ManyToManyField(blank=True, to='parity_app.Light'),
        ),
        migrations.AlterField(
            model_name='room',
            name='sensor_temperature_indoor',
            field=models.ManyToManyField(blank=True, to='parity_app.SensorTemperatureIndoor'),
        ),
        migrations.AlterField(
            model_name='sensortemperatureindoor',
            name='temperature',
            field=models.IntegerField(default=17, null=True),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='thermostat_mode',
            field=models.CharField(choices=[('OFF', 'Off'), ('COOL', 'Cool'), ('HEAT', 'Heat'), ('FAN_OFF', 'Fan-on'), ('AUTO', 'Auto')], default='OFF', max_length=10),
        ),
    ]
